//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DIP1.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DIP1TYPE                    129
#define IDD_DIALOG1                     130
#define IDD_DIALOG2                     131
#define IDD_DIALOG3                     132
#define IDD_DIALOG4                     133
#define IDD_DIALOG5                     134
#define IDD_DIALOG6                     135
#define IDD_DIALOG7                     136
#define IDD_DIALOG8                     137
#define IDD_DIALOG9                     138
#define IDD_DIALOG10                    139
#define IDD_DIALOG11                    142
#define IDD_DIALOG12                    143
#define IDD_DIALOG13                    144
#define IDR_MOUSE_RIGHT                 145
#define IDD_HIST_DIALOG                 146
#define IDC_CURSOR1                     149
#define IDD_DIALOG14                    150
#define IDC_hor                         1000
#define IDC_ver                         1001
#define IDC_SPIN_hor                    1004
#define IDC_SPIN_ver                    1005
#define IDC_Threshold                   1006
#define IDC_A                           1007
#define IDC_B                           1008
#define IDC_ZOOMX                       1009
#define IDC_ZOOMY                       1010
#define IDC_HIGH                        1010
#define IDC_LOW                         1011
#define IDC_LOG_COEFF                   1013
#define IDC_POWER_C                     1014
#define IDC_POWER_GAMMA                 1015
#define IDC_TEMP_HEIGHT                 1017
#define IDC_TEMP_WIDTH                  1018
#define IDC_NOISE_DADIO                 1018
#define IDC_TEMPLATE_SIZE               1019
#define IDC_HOR_SPIN                    1024
#define IDC_VER_SPIN                    1025
#define IDC_TEMPLATESIZE_SPIN           1026
#define IDC_THRESHOLD_SPIN              1027
#define IDC_A_SPIN                      1028
#define IDC_B_SPIN                      1029
#define IDC_R                           1033
#define IDC_G                           1034
#define IDC_BRIGHTCHANGE                1034
#define IDC_HOR_SCROLLBAR               1035
#define IDC_WIDTH                       1036
#define IDC_HEIGHT                      1037
#define IDC_COORD                       1038
#define IDC_IMAGEWIDTH                  1039
#define IDC_IMAGEHEIGHT                 1040
#define IDC_FILEPATH                    1042
#define IDC_BUTTONSCAN                  1043
#define IDC_NBITS                       1044
#define ID_OPEN_IMAGE                   32771
#define ID_DIP                          32772
#define ID_SAVE_IMAGE                   32773
#define ID_IMAGE_TRANSLATION            32774
#define ID_RGB2_GRAY                    32775
#define ID_IMAGE_THRESHOLD              32777
#define ID_IMAGE_CONTRARY               32778
#define ID_Robert_Edge                  32779
#define ID_Sobel_Edge                   32780
#define ID_PreWitt_Edge                 32781
#define ID_Gauss_Lap_Edge               32782
#define ID_IMAGE_LINEAR                 32783
#define ID_IMAGE_MIRRORHOR              32788
#define ID_IMAGE_MIRRORVER              32789
#define ID_IMAGE_ZOOM                   32790
#define ID_IMAGE_BIG                    32791
#define ID_IMAGE_SMALL                  32792
#define ID_IMAGE_TRANSPOSE              32793
#define ID_WINDOW_TRANSLATION           32794
#define ID_IMAGE_LOG                    32795
#define ID_POWER                        32796
#define ID_AREA_AVERAGE                 32797
#define ID_WEIGHT_AVERAGE               32798
#define ID_MEDIAN_FILTER                32799
#define ID_MAX_FILTER                   32800
#define ID_MIN_FILTER                   32801
#define ID_PLUS_MEDIANFilter            32802
#define ID_IMAGE_SALTPEPPER             32804
#define ID_PROFILE_DETECT               32805
#define ID_SHOW_ORIGIN_IMAGE            32808
#define ID_GRAY2_RGB                    32809
#define ID_SHOW_PREIMAGE                32810
#define ID_UNDO                         32811
#define ID_KRISCH_EDGE                  32813
#define ID_RGB_ADDCOLOR                 32814
#define ID_BRIGHT_CHANGE                32815
#define ID_MOSAIC                       32816
#define ID_IMAGE_RANDNOISE              32818
#define ID_R_COLOR                      32819
#define ID_G_COLOR                      32820
#define ID_B_COLOR                      32821
#define ID_TO_DOWNSCAN                  32822
#define ID_TO_UPSCAN                    32823
#define ID_TORIGHTSCAN                  32824
#define ID_TOLEFTSCAN                   32825
#define ID_IMAGE_HistogramEqualization  32826
#define ID_SAVE_DATA                    32827
#define ID_IMAGE_FOURIER                32828
#define ID_RGB2_HSI                     32829
#define ID_GRAY_HIST                    32830
#define ID_R_HIST                       32831
#define ID_G_HIST                       32832
#define ID_B_HIST                       32833
#define ID_LAPLACIAN_EDGE               32842
#define ID_OTSU                         32843
#define ID_APAPTIVE_THRESHOLD           32845
#define ID_SHUIPING_EROSION             32848
#define ID_CHUIZHI_EROSION              32849
#define ID_SHUIPING_DILATION            32850
#define ID_CHUIZHI_DILATION             32851
#define ID_DONGXI_EROSION               32852
#define ID_XIDONG_EROSION               32853
#define ID_DONGXI_DILATION              32854
#define ID_XIDONG_DILATION              32855
#define ID_IMAGE_EROSION                32856
#define ID_IMAGE_DILATION               32857
#define ID_TEST_OPENCV                  32862
#define ID_CV_FACEDETECTION             32863
#define ID_CV_ERODE                     32864
#define ID_CV_DILATE                    32865
#define ID_CV_CORNERDETECTIPN           32866
#define ID_CV_SOBELEDGE                 32867
#define ID_CV_CANNY_EDGE                32868
#define ID_CV_SPLIT                     32869
#define ID_CV_LAPLACIAN                 32870
#define ID_CV_PCFACEDETECTION           32871
#define ID_FACE_DETECTIONYUSHIQI        32872
#define ID_CV_SIMPLEBLUR                32873
#define ID_CVSIMPLENOSCALEBLUR          32874
#define ID_CVMEDIANBLUR                 32875
#define ID_CVGAUSSIANBLUR               32876
#define ID_CVPLOTHIST                   32878
#define CD_CVHISTEqualize               32879
#define ID_NEW_IMAGE                    32880
#define ID_CLEAR_IMAGE                  32881

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32882
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
